stages:                  
  - build
  - deploy

build_linux:
  image: infradb.inpark.kr:5000/infra/golang:latest
  stage: build
  only:
    changes:
      - ansible.gitlab-ci.yml
  script:
    - go version
    - make cc 
    
  artifacts:
    paths:
      - bin
      
  tags:
    - infra
